### PR TITLE
y tho?

### PR DESCRIPTION
**Pull request by jhofm**
?

### CODE REVIEW

**Comment by shyim** [comment]
This package is already provided by shopware. It helps to reduce package size 😉

**Comment by jhofm** [comment]
i'm currently going more towards a single set of dependencies instead of the whole plugins requiring their own autoloaders with contradicting dependencies whenever they want mess. the problem with that is that this dependency substitution leads to corrupt composer.lock files if the build instance has this plugin but the target hasn't. i spent about an hour today wondering how my builds just broke ^^. just suggesting the implications for "special" users might not be worth the couple of saved kbs of data. ;)

**Comment by shyim** [comment]
Could you update then also the composer.lock 😄

**Comment by jhofm** [comment]
not on this device i can't, but i'll rebase this to something more properly tomorrow.  ^^

**Comment by jhofm** [comment]
i changed the commit message to something more sensible. regarding the composer.lock file: i don't see any; am i missing something?

**Pull request merged**
